### ISSUE TITLE
Decide on the name of the python package

### ISSUE THREAD

**Issue by nbeloglazov** [belaudiobooks/belorthography#4]
What should we name python package? I think the name should:
1. Be specific enough to make it clear it's related to Belarusian language. 
2. Be generic enough to support various conversions of Belarusian language.

For (2) we originally were planning to implement only lacinization: conversion of cyrillic text to lacinka. But after talking to a specialist it seems like we'll have to implement conversion for official (narkamauka) to classic (tarashkevica) modes. That's necessary for proper lacinization later.

Some ideas (I don't have a good idea at the moment).

* belalphabet
* belconversion
* belorthography (see [wiki](https://en.wikipedia.org/wiki/Tara%C5%A1kievica))

@frombrest do you have ideas?

**Comment by nbeloglazov** [comment]
I haven't done any work on this issue. And I don't think I'm going to spend more time on it. Instead let's just decide on a name, so that we can do an alpha release of the package. 

I'm planning to go with belorthography as the package name. 

@frombrest any concerns?

**Comment by frombrest** [comment]
I am ok, but that sounds a bit like library going to be spell-checking rather than transliteration/metagraphy conversion.

**Comment by nbeloglazov** [comment]
Do you have other preferences/suggestions for the name? I agree that belorthography feels more generic. But well, who knows. Maybe  it will become more generic. For example I think we'll need to implement orthography detection - given text infer whether it's cyrillic or latinica.

**Comment by frombrest** [comment]
Let's go with `belorthography` .... In case of critical necessity it is possible to deprecate this library and migrate clients to another one with new name.
